-'''		
 -    api_config.py		
 -    Calypso Leonard, Tresa Xavier, YingYing Wang		
 -    Jeff Ondich, 25 April 2016		
 -    Database login info for the "Board Game Finder" sample web		
 -    app for CS 257, Winter 2018.		
 -'''		
 -		
 -		
 -database = 'wangc2'		
 -user = 'wangc2'		
 -password = 'towel672nose'
